# general setup
TILE_SIZE = 64
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
ANIMATION_SPEED = 8

# colours
SKY_COLOUR = '#ddc6a1'
SEA_COLOUR = '#92a9ce'
HORIZON_COLOUR = '#f5f1de'
HORIZON_TOP_COLOUR = '#d1aa9d'
LINE_COLOUR = 'black'